name: ipytone-dev
channels:
  - conda-forge
dependencies:
  - black
  - ipywidgets>=7.6
  - jupyterlab=3
  - numpy
  - pip
  - pre-commit
  - pytest
  - pytest-mock
  - ruff
  - traittypes
  - yarn
  - wheel
  - twine
  - traittypes
